os: Visual Studio 2017

test: off

after_build:
  - ps: Update-AppveyorBuild -Version "$($env:Version)"
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $files = Resolve-Path .\artifacts\test-results\*.trx;
  - ps: >- 
          foreach($file in $files) 
          { 
            echo "Uploading $file to appveyor"
            $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $file) 
          }

artifacts:
- path: '.\artifacts\packages\*.nupkg'

for:
  -
    branches:
      only:
        - master

    build_script:
      - ps: .\build.ps1 -ScriptArgs '-task="Server" -nugetApiKey="$($env:Nuget_ApiKey)" -isLocal=false'
  
    on_failure:
      - ps: Update-AppveyorBuild -Version "$($env:Version)-$(Get-Date -format HHmmss)-failed"
  -
    branches:
      except:
        - master
  
    build_script:
      - ps: .\build.ps1 -ScriptArgs '-task="Server" -nugetApiKey="$($env:Nuget_ApiKey)" -buildNumber="-$($env:APPVEYOR_REPO_BRANCH)$($env:APPVEYOR_BUILD_NUMBER)" -isLocal=false'