os: Visual Studio 2017

test: off

after_build:
  - ps: echo "current version is $($env:semVersion)"
  - ps: Update-AppveyorBuild -Version "$($env:semVersion)"
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: Resolve-Path .\artifacts\test-results\*.trx | ForEach-Object { $wc.UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", $_) }

artifacts:
- path: '.\artifacts\packages\*.nupkg'

for:
  -
    branches:
      only:
        - master

    build_script:
      - ps: .\build.ps1 -ScriptArgs '-task="Server" -nugetApiKey="$($env:Nuget_ApiKey)" -isLocal=false'
  
    on_failure:
      - ps: Update-AppveyorBuild -Version "$($env:semVersion)-$(Get-Date -format HHmmss)-failed"
  -
    branches:
      except:
        - master
  
    build_script:
      - ps: .\build.ps1 -ScriptArgs '-task="Server" -nugetApiKey="$($env:Nuget_ApiKey)" -buildNumber="-$($env:APPVEYOR_REPO_BRANCH)$($env:APPVEYOR_BUILD_NUMBER)" -isLocal=false'